### PR TITLE
Details for events and organisations

### PR DESCRIPTION
**Pull request by ayakiri**
Jira:
https://woloapp.atlassian.net/browse/WOLO-243

- details for organisation
- details for events
- no styling

### CODE REVIEW

**Comment by ayakiri** [comment]
It's in admin panel,fyi

**Review by KinWaj — APPROVED** [review]
district id doesn't like us 
image

**Comment by ayakiri** [comment]
> district id doesn't like us image

We don't like distrct is as well!

**Review by KinWaj — COMMENTED** [review]
image
details is out of the table, plz fix it <3

**Pull request merged**
