### PR TITLE
WOLO-163-fixing create event

### PR DESCRIPTION
**Pull request by Filiposki54**
- There is a form without validation
- No style yet
- needs better category handler

### CODE REVIEW

**Comment by ayakiri** [comment]
image
Why starttime and end time for whole event? Not shiift but an event?

**Comment by ayakiri** [comment]
> image Why starttime and end time for whole event? Not shiift but an event?

Nevermind, I'm dumb. Desperatly needs better styling

**Comment by ayakiri** [comment]
image
Json wygląda ok, ale i tak nie przechodzi, trzeba zerknąć czy wina Be czy Fe

**Comment by ayakiri** [comment]
{
  "name": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "description": "Are you passionate about making a positive impact on the lives of animals in need? Join us in our mission to provide compassionate care and support for animals at our local animal shelter.",
  "organisationId": 1,
  "date": "2025-05-01",
  "cityId": 1,
  "categories": [
    1
  ],
  "isPeselVerificationRequired": true,
  "isAgreementNeeded": true,
  "imageUrl": "",
  "shifts": [
    {
      "startTime": "15:00:00",
      "endTime": "18:00:00",
      "capacity": 5,
      "isLeaderRequired": true,
      "requiredMinAge": 12,
      "shiftDirections": "Left Side of Building",
      "street": "Broadway",
      "homeNum": "123",
      "districtId": 1
    }
  ]
}


Znalazłam działający JSon

**Review by KinWaj — COMMENTED** [review]
district and city are not connected, there's no center in krakow for example, it would be nice if u would select the city, only districts that are in that city will show up
image
image

**Review by KinWaj — COMMENTED** [review]
When I added events, they didn't come through (even after CORS was added), and for the moment they were going through but they were not showing up on the details page :c

**Review by KinWaj — APPROVED** [review]
It works :)

**Pull request merged**
