### PR TITLE
Wolo 260 events ongoing and past

### PR DESCRIPTION
**Pull request by ayakiri**
Jira:
https://woloapp.atlassian.net/browse/WOLO-260

- volunteers past / current events
- organisation past / current events
- no button sign off/delete/edit if it's in past
- translations
- clicking on event name in list redirects to /details
- organisations name displayed n banner
- info if there are no events to display

### CODE REVIEW

**Review by KinWaj — COMMENTED** [review]
image
it is not redirecting to the event details

**Review by KinWaj — COMMENTED** [review]
image
when filters are set, the msg for no events found is displayed referring to 'info if there are no events to display'

**Comment by ayakiri** [comment]
> image when filters are set, the msg for no events found is displayed referring to 'info if there are no events to display'

It's for when there are no events to display on volunteer page/organizer page, not All events

**Review by KinWaj — COMMENTED** [review]
image
button for sign in onto the event is still visible for organiser

**Comment by ayakiri** [comment]
> image button for sign in onto the event is still visible for organiser

Yes, I thought we agreed to it? Organiser as in the person behind the organisation can still join their event as themselves?

**Review by KinWaj — COMMENTED** [review]
Look at the date : 
image
could they really sign off from prev event ?

**Comment by ayakiri** [comment]
> Look at the date : image could they really sign off from prev event ?

It was updated in other PR, I will merge changes from main now

**Review by KinWaj — APPROVED** [review]
Now i can approve :3

**Pull request merged**
